import Head from 'next/head'
import styles from '../../styles/soporte.module.css'
import { useEffect, useState } from "react"
import Header from '../header';

export default function Soporte() {

    return(<div className={styles.container}>
        <Head>
          <title>Modulo de soporte</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <Header></Header>

        <div className={styles.titulos}>
              <div>
                Abierto
              </div>
              <div>
                En analisis
              </div>
              <div>
                Derivado
              </div>
              <div>
                Resuelto
              </div>
              <div>
                Cancelado
              </div>
            </div>
        <main className={styles.main}>
   
            <a href='/moduloSoporte/ticketCreate'><button>CREAR TICKET</button></a>

        </main>
  
        <footer className={styles.footer}>

        </footer>
      </div>
    );
  }
