import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Create() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TPG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
            <div className={styles.headerIzq}>PSA</div>
            <div className={styles.headerDer}>
            </div>
        </header>

      <main className={styles.main}>
        <h1>Nuevo Ticket</h1>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
