import Head from 'next/head'


export default function Head_({nombre}: {nombre:string}) {    

    return (
        <Head>
            <title>{nombre}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
    )
  }
  