import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TPG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido
        </h1>

        <div className={styles.grid}>
          
          <a href="/soporte" className={styles.card}>
            <h2>Modulo de Soporte</h2>
            <p>Lorem ipsum bla bla</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Modulo de Recursos</h2>
            <p>Bla bla bla</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Modulo de Proyectos</h2>
            <p>bla</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
