import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Soporte() {
    return(<div className={styles.container}>
        <Head>
          <title>Modulo de soporte</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <header className={styles.header}>
            <div className={styles.headerIzq}>PSA</div>
            <div className={styles.headerDer}>
                <div>Buscador</div> 
                <div>Filtro</div>
            </div>
        </header>
        <main className={styles.main}>

            <button>CREAR TICKET</button>

        </main>
  
        

        <footer className={styles.footer}>

        </footer>
      </div>
    );
  }