import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Soporte() {
    return(<div className={styles.container}>
        <Head>
          <title>Modulo de soporte</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <header className={styles.header}>
            <div className={styles.headerIzq}>PSA</div>
            <div className={styles.headerDer}>
                <div>Buscador</div> 
                <div>Filtro</div>
            </div>
        </header>
        
        <div className={styles.titulos}>
              <div>
                Abierto
              </div>
              <div>
                En analisis
              </div>
              <div>
                Derivado
              </div>
              <div>
                Resuelto
              </div>
              <div>
                Cancelado
              </div>
            </div>
        <main className={styles.main}>
   
            <a href='/create'><button>CREAR TICKET</button></a>

        </main>
  
        <footer className={styles.footer}>

        </footer>
      </div>
    );
  }